import type { Metadata } from "next";
import "../globals.css";
import Header from "./(protected)/home/_components/header/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased font-sans">
      <body className="min-h-full flex flex-col bg-yellow-15">
        <header>
          <Header level={1} progress={20}></Header>  
        </header>
        
        {children}
      </body>
    </html>
  );
}
